### ISSUE TITLE
root - ERROR - Killing request for url

### ISSUE THREAD

**Issue by raonyguimaraes** [Ensembl/postgap#163]
I am getting this error when trying to run postgap for 100 variants:

python POSTGAP.py  --summary_stat input.tsv --database_dir databases/
08/06/2020 12:38:05 PM - root - ERROR - Killing request for url: http://rest.ensembl.org/eqtl/variant_name/homo_sapiens/rs7523364?content-type=application/json;statistic=p-value

URL opens just fine in the browser.

**Comment by dzerbino** [comment]
Hello @raonyguimaraes ,

That's curious, could you please send me the entire log?

Thank you,

Daniel

**Comment by raonyguimaraes** [comment]
Here is the full log file: [postgap.log](https://github.com/Ensembl/postgap/files/5040219/postgap.log)

It's mostly complaining about the LD matrix: 08/06/2020 05:03:46 PM - root - ERROR - LD matrix is identity matrix!

This error is probably because my ulimit values were too low, so let me increase that and run it again!

Traceback (most recent call last):                                                                                
  File "POSTGAP.py", line 690, in <module>                                                                        
    main()                                                                                                        
  File "POSTGAP.py", line 153, in main                                                                            
    formatted_results = pretty_output(res, options.population)                                                    
  File "POSTGAP.py", line 435, in pretty_output                                                                   
    content = filter(lambda X: len(X) > 0, [pretty_cluster_association(association, population) for association in
 associations])                                                                                                   
  File "POSTGAP.py", line 447, in pretty_cluster_association                                                      
    results = genecluster_association_table(association, population)                                              
  File "POSTGAP.py", line 466, in genecluster_association_table                                                   
    ld_snp_ids, r_matrix = postgap.LD.get_pairwise_ld(association.cluster.ld_snps, population)                    
  File "***REDACTED****/postgap/lib/postgap/LD.py", line 241, in get_pairwise_ld             
    process = Popen(ld_comm, stdout=PIPE, stderr=PIPE)                                                            
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__                                                  
    errread, errwrite)                                                                         
  File "/usr/lib/python2.7/subprocess.py", line 928, in _execute_child                                            
    errpipe_read, errpipe_write = self.pipe_cloexec()                                          
  File "/usr/lib/python2.7/subprocess.py", line 865, in pipe_cloexec
    r, w = os.pipe()
OSError: [Errno 24] Too many open files
        
real    190m44.836s                                  
user    24m45.199s                                   
sys     11m58.285s

**Comment by dzerbino** [comment]
OK let me know.

Cheers,

Daniel
