### ISSUE TITLE
postgap.EFO.children()

### ISSUE THREAD

**Issue by dzerbino** [Ensembl/postgap#75]
Hello @mn1 ,

postgap.EFO.children() does not seem to work anymore, could you please have a look?

Thanks,

Danie

**Comment by mn1** [comment]
How are you running postgap?

I ran:

`python POSTGAP.py --database_dir /nfs/nobackup/ensembl/mnuhn/postgap/databases/ --diseases "diabetes" --output diabetes.tsv
`

And it worked:

```
...
05/12/2017 12:21:07 PM - postgap.Integration - INFO - Searching for regulatory data on 154 SNPs in all databases
05/12/2017 12:21:07 PM - root - INFO - Found 5 regulatory SNPs among 154 in all databases
05/12/2017 12:21:07 PM - postgap.Integration - INFO -   Found 280 genes associated around GWAS SNP rs10882100
05/12/2017 12:21:08 PM - postgap.Integration - INFO -   Found 81155 genes associated to all clusters
(postgap_python2.7)[mnuhn@ebi-cli-003 postgap_clean_checkout]$ echo $?
0
(postgap_python2.7)[mnuhn@ebi-cli-003 postgap_clean_checkout]$ git branch
* master
(postgap_python2.7)[mnuhn@ebi-cli-003 postgap_clean_checkout]$ cat .git/config 
[core]
        repositoryformatversion = 0
        filemode = true
        bare = false
        logallrefupdates = true
[remote "origin"]
        url = https://github.com/Ensembl/postgap
        fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
        remote = origin
        merge = refs/heads/master
(postgap_python2.7)[mnuhn@ebi-cli-003 postgap_clean_checkout]$ git pull
Already up-to-date.

```

**Comment by dzerbino** [comment]
```
ebi-cli-003.ebi.ac.uk> python POSTGAP.py  --database_dir /homes/zerbino/hps/postgap/databases --efos EFO_0000094 --output /homes/zerbino/hps/postgap/results/EFO_0000094.txt
05/12/2017 03:24:15 PM - root - ERROR - Failed to get proper response to query http://www.ebi.ac.uk/ols/api/ontologies/efo/terms/EFO_0000094
05/12/2017 03:24:15 PM - root - ERROR - With headers:{'Content-Type': 'application/json'}
05/12/2017 03:24:15 PM - root - ERROR - Error code: 404
05/12/2017 03:24:15 PM - root - ERROR - Got status code 404.
Traceback (most recent call last):
  File "POSTGAP.py", line 296, in <module>
    main()
  File "POSTGAP.py", line 82, in main
    options = get_options()
  File "POSTGAP.py", line 156, in get_options
    options.efos = concatenate(map(postgap.EFO.children, options.efos))
  File "/homes/zerbino/utils/postgap/lib/postgap/EFO.py", line 175, in children
    hash = postgap.REST.get(server, ext)
  File "/homes/zerbino/utils/postgap/lib/postgap/REST.py", line 92, in get
    r.raise_for_status()
  File "/homes/zerbino/utils/anaconda/lib/python2.7/site-packages/requests/models.py", line 909, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://www.ebi.ac.uk/ols/api/ontologies/efo/terms/EFO_0000094
```

**Comment by mn1** [comment]
Cool, thanks, that fails for me too.

**Comment by mn1** [comment]
It works, if I use the IRI instead of the efo accession only:

`python POSTGAP.py  --database_dir /homes/zerbino/hps/postgap/databases --efos http://www.ebi.ac.uk/efo/EFO_0000094 --output EFO_0000094.txt`

**Comment by dzerbino** [comment]
Is there a general way of determining IRIs for EFOs, Orphanet, etc?

**Comment by mn1** [comment]
I was just looking for a programmatic way to do that, but I don't see it.

It can be done manually via
http://www.ebi.ac.uk/efo/

**Comment by mn1** [comment]
Ah, here it is:

http://www.ebi.ac.uk/ols/api/search?q=EFO_0000094&ontology=efo

**Comment by mn1** [comment]
Nah, there must be something better.

**Comment by mn1** [comment]
I have asked on the efo-users mailing list.

**Comment by mn1** [comment]
I got a reply from Simon Jupp. This is how to get them:

http://www.ebi.ac.uk/ols/api/ontologies/efo/terms?short_form=EFO_0002795

I'll add this to postgap.
